### ISSUE TITLE
Alpha channel in HEX

### ISSUE THREAD

**Issue by zumm** [kleinfreund/vue-accessible-color-picker#17]
## Steps to reproduce
Hex input field have alpha channel even if alpha channel option is set to 'hide'.

## Current result
Hex code with alpha channel.

## Expected result
Hex code without alpha channel.

## Environment
- **vue-accessible-color-picker** version: 4.0.0

**Comment by kleinfreund** [comment]
I’ve implemented a fix for this in https://github.com/kleinfreund/vue-accessible-color-picker/commit/b301c5bee128600fc2141906deaeeb7272cb5b2a. It was released in package version [4.0.1](https://github.com/kleinfreund/vue-accessible-color-picker/releases/tag/v4.0.1).

**Comment by kleinfreund** [comment]
> Alpha channel is still in hex property of color object of color-change event. Is it ok?

@zumm That is intentional, yes. In the `color-change` event, the `cssColor` property will have a value without alpha channel while colors in the `colors` property will have a value with alpha channel.

**Comment by zumm** [comment]
cssColor isn't the way for me since it respects color input mode. I want to get hex without alpha channel regardless of color input mode.

Also it seems to be broken. See that example - https://codesandbox.io/s/ancient-water-u2uvtr?file=/src/App.vue
Hex color is getting clipped.

**Comment by zumm** [comment]
Yes, currently i'm using code like that to get hex without alpha channel. It is not very convenient, but ok.

New patch brings new bugs. Try to update vue-accessible-color-picker version in my previous example and select color by color-space-thumb. Hue slider goes crazy.

Also i found another bug - hex code is getting clipped while copying.

**Comment by kleinfreund** [comment]
@zumm Hey. Thank you for this follow-up report. I believe your issue has the same cause as what was reported in #18. After fixing that issue, opening [your demo](https://codesandbox.io/s/busy-framework-itkl23) again and installing v4.0.3, I can no longer reproduce either the color jumping around in the hue slider or the copy button copying a clipped color. Would you mind trying it again? Thank you for your patience.
