### ISSUE TITLE
Test coverage reporting in pull requests & readme badge

### ISSUE THREAD

**Issue by kleinfreund** [kleinfreund/vue-accessible-color-picker#2]
## Description

I’d like to have a test coverage badge in the readme to give package users a sense of the state this project is in. Users should be able to see the percentage of code that is covered by tests.

I would also like to have a mechanism on pull requests that allows repository maintainers to see the test coverage of the pull request’s branch.

## Motivation

- If test coverage gets worse over time, users should be able to tell easily without the need run the test suite themselves.
- If test coverage in pull request is getting worse, it’s nice for repository maintainers to see that easily and potentially ask for tests to be added to the pull request.

## Further considerations

I had a short look at a few code coverage services ([Codecov](https://codecov.io/), [Coveralls](https://coveralls.io/), and [Codacy](https://www.codacy.com/)). They are definitely able to provide these features. However, they only provide single sign-on mechanisms for creating an account and require me to hand over a substantial amount of access to my GitHub account right at the time of creating an account. I really dislike that, in particular it’s not clear whether this degree of access is actually warranted for my specific use case.

**Comment by underscoredotspace** [comment]
I see you're already hosting a demo on Netlify. I bet you could generate an SVG at build-time that could be linked to in the readme. Not sure about the PR part though. More thought required there.

**Comment by kleinfreund** [comment]
I don’t currently consider this a priority and am therefor closing this issue for now.
