### ISSUE TITLE
Basic install doesn't work

### ISSUE THREAD

**Issue by paulkarpenko** [kleinfreund/vue-accessible-color-picker#21]
I've copied and pasted basic usage from the docs, but I'm not able to get the plugin to run with basic install and import. I've reproduced my issue in the codesandbox below? Is there something wrong with how I'm importing it?

```
<template>
  <div id="app">
    <ColorPicker />
  </div>
</template>

<script>
  import { ColorPicker } from "vue-accessible-color-picker";

  export default {
    name: "App",
    components: {
      ColorPicker,
    },
  };
</script>
```

## Steps to reproduce
https://codesandbox.io/s/vue-accessible-color-picker-0dr3tv?file=/src/App.vue

## Current result
```
(0 , $csb__vue.createTextVNode) is not a function
```

## Expected result
Basic install works

## Environment

- **vue-accessible-color-picker** version: 4.0.3 and 3.3.1

**Comment by kleinfreund** [comment]
Thank you for taking the time to report this problem.

As of version [v2.0.0](https://github.com/kleinfreund/vue-accessible-color-picker/releases/tag/v2.0.0), the package was migrated to be compatible with Vue.js 3. At the same time, support for Vue.js 2 was dropped. To use this package with Vue.js 2, a version before v2.0.0 will habe to be used.

I also realize now that the README.md file doesn’t explicitly mention Vue.js 3 which is something I will add now as it isn’t clear that only Vue.js 3 is supported.

**Comment by paulkarpenko** [comment]
@kleinfreund thank you for your reply. I downgraded to v1.1.2 and it works!
