### ISSUE TITLE
Incorrect initialization if color is white

### ISSUE THREAD

**Issue by zumm** [kleinfreund/vue-accessible-color-picker#22]
Gradient on `vacp-color-space` doesn't appear if initialization color is `#ffffff`. Demo is [here](https://codesandbox.io/s/naughty-mountain-9gvrfn?file=/src/App.vue).

**Comment by kleinfreund** [comment]
In 9ec0b6442344a1553974f9a05594765bc69dc40a, I fixed an issue with initializing the color picker when using the internal default color (which happens to be white). This fix was released in version [4.0.4](https://github.com/kleinfreund/vue-accessible-color-picker/releases/tag/v4.0.4). Can you please check whether this fixes your issue?

Also, please keep the bug report template in place and provide full reproduction steps. I do appreciate you providing a reproduction in form of a demo, but it’s nice to not rely on guess work on how the issue manifests.
