### ISSUE TITLE
Types for typescript

### ISSUE THREAD

**Issue by johndcarmichael** [kleinfreund/vue-accessible-color-picker#6]
Looks way cleaner and easier to use than vue-color but cannot use as there are no types - it is this already in progress?

**Comment by kleinfreund** [comment]
I do want to add types to the project, yes. I’m also considering to write it in TypeScript entirely but for that, I want to finish the migration to Vue.js 3 first. The migration to Vue.js 3 is currently blocked on a couple of issues documented in https://github.com/kleinfreund/vue-accessible-color-picker/issues/4 so this will have to wait.

I’ll have a look at what I can do to expose type definitions for the project with the current major version 1.

**Comment by kleinfreund** [comment]
I added some basic type definitions to the project in [v1.1.0](https://github.com/kleinfreund/vue-accessible-color-picker/releases/tag/v1.1.0). Many parts of the code base were also covered with type annotations. The currently existing type definitions should be sufficient to annotate most things in relation to this plugin, but I don’t consider this work to be quite done, yet. I will see how the typing situation can be improved both in the source code and for package consumers.
